version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"

  server:
    build: server/
    depends_on:
      - db
    ports:
      - "8080:8080"